# Generated by Django 5.2.4 on 2025-09-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source_wikipedia", "0003_crawljob_spider_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="RankingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_persona", models.CharField(max_length=100)),
                ("user_expertise", models.CharField(max_length=100)),
                ("query", models.TextField()),
                ("documents", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("ranked_documents", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
