# Generated by Django 5.2.4 on 2025-09-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("source_wikipedia", "0004_rankingjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="rankingjob",
            name="external_job_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
