# Generated by Django 5.2 on 2025-04-30 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("source_wikipedia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawljob",
            name="mongodb_db",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="IndexJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("mongodb_db", models.CharField(max_length=100)),
                ("mongodb_collection", models.CharField(max_length=100)),
                ("elastic_index", models.CharField(max_length=100)),
                ("batch_size", models.IntegerField(default=100)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crawl_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="index_jobs",
                        to="source_wikipedia.crawljob",
                    ),
                ),
            ],
        ),
    ]
