# Generated by Django 5.2.4 on 2025-07-12 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyntheticUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "persona",
                    models.CharField(
                        choices=[
                            ("developer", "Developer"),
                            ("data_scientist", "Data Scientist"),
                            ("business_analyst", "Business Analyst"),
                            ("researcher", "Researcher"),
                            ("student", "Student"),
                            ("hr", "HR"),
                            ("historian", "Historian"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "expertise_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("expert", "Expert"),
                        ],
                        max_length=20,
                    ),
                ),
                ("importance", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preference_type", models.CharField(max_length=50)),
                ("preference_value", models.CharField(max_length=200)),
                ("weight", models.FloatField(default=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="user.syntheticuser",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "preference_type", "preference_value")},
            },
        ),
    ]
