# Generated by Django 5.2.4 on 2025-07-12 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField()),
                ("entity", models.JSONField()),
                ("doc_url", models.URLField(blank=True, max_length=500)),
                ("doc_title", models.CharField(max_length=500)),
                ("relevance_score", models.FloatField()),
                ("rank", models.IntegerField()),
                ("user_persona", models.CharField(max_length=50)),
                ("user_expertise", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_data",
                        to="user.syntheticuser",
                    ),
                ),
            ],
            options={
                "ordering": ["user", "query", "rank"],
                "indexes": [
                    models.Index(
                        fields=["user", "query"], name="user_traini_user_id_2b2a8e_idx"
                    ),
                    models.Index(
                        fields=["relevance_score"],
                        name="user_traini_relevan_1fd86b_idx",
                    ),
                    models.Index(fields=["rank"], name="user_traini_rank_c5120b_idx"),
                ],
            },
        ),
    ]
