# Generated by Django 5.2.4 on 2025-07-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_trainingdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syntheticuser",
            name="persona",
            field=models.CharField(
                choices=[
                    ("developer", "Developer"),
                    ("data_scientist", "Data Scientist"),
                    ("business_analyst", "Business Analyst"),
                    ("researcher", "Researcher"),
                    ("student", "Student"),
                    ("hr", "HR"),
                    ("historian", "Historian"),
                    ("marketing", "Marketing"),
                    ("finance", "Finance"),
                    ("designer", "Designer"),
                    ("healthcare", "Healthcare"),
                    ("educator", "Educator"),
                ],
                max_length=50,
            ),
        ),
    ]
