apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler
  labels:
    app: crawler
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crawler
  template:
    metadata:
      labels:
        app: crawler
    spec:
      containers:
        - env:
            - name: MONGODB_URI
              value: mongodb://root:example@mongodb:27017/
          image: search-engine-crawler:latest
          imagePullPolicy: Never
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:5000/health
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 10
          name: crawler
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "4Gi"
            requests:
              memory: "1Gi"
