apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  clusterIP: None  # Make it headless
  ports:
    - name: "http"
      port: 9200
      targetPort: 9200
    - name: "transport"
      port: 9300
      targetPort: 9300
  selector:
    app: elasticsearch
