apiVersion: apps/v1
kind: StatefulSet    # ✅ Change to StatefulSet
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
spec:
  serviceName: "elasticsearch"  # ✅ Required for StatefulSet
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
          image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:9200
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 10
          name: elasticsearch
          ports:
            - containerPort: 9200
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-data
  volumeClaimTemplates:  # ✅ Now this works with StatefulSet
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
