apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower
  labels:
    app: flower
spec:
  replicas: 1  # Usually just 1 replica for admin tools
  selector:
    matchLabels:
      app: flower
  template:
    metadata:
      labels:
        app: flower
    spec:
      containers:
      - name: flower
        image: mher/flower:latest
        ports:
        - containerPort: 5555
        env:
        - name: CELERY_BROKER_URL
          value: "redis://redis:6379/0"
        - name: FLOWER_PORT
          value: "5555"
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "128Mi"
