apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: flower
  name: flower
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flower
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: flower
    spec:
      containers:
        - env:
            - name: CELERY_BROKER_URL
              value: redis://redis:6379/0
            - name: FLOWER_PORT
              value: "5555"
          image: mher/flower
          name: flower
          ports:
            - containerPort: 5555
              protocol: TCP
      restartPolicy: Always
