apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: indexer
  name: indexer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: indexer
  template:
    metadata:
      labels:
        app: indexer
    spec:
      containers:
        - env:
            - name: ELASTICSEARCH_URI
              value: http://elasticsearch:9200
            - name: MONGODB_URI
              value: mongodb://root:example@mongodb:27017/
          image: search-engine-indexer:latest
          imagePullPolicy: Never
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:5000/health
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 10
          name: indexer
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "4Gi"
            requests:
              memory: "1Gi"
