apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-webserver-config
data:
  default.conf: |
    upstream django_backend {
        server localhost:8000;
        keepalive 32;
    }

    server {
        listen 80;
        server_name localhost;
        client_max_body_size 100M;

        # Static files served by nginx
        location /static/ {
            alias /app/webserver/search/collected_static/;
        }

        # Everything else proxied to Django
        location / {
            proxy_pass http://django_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 10s;
            proxy_send_timeout 30s;
            proxy_read_timeout 30s;
        }
    }
