apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  clusterIP: None  # Make it headless for StatefulSet
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    app: redis  # This should match your StatefulSet labels
