apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 80
    - name: "django-debug"
      port: 8000
      targetPort: 8000
  selector:
    app: webserver
