apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver
  name: webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      initContainers:
      - name: migrate
        image: search-engine-webserver:latest
        imagePullPolicy: Never
        command: [ 'sh', '-c', 'cd /app/webserver/search && python manage.py migrate' ]
        env:
          - name: db_psw
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: password
          - name: db_user_name
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: name
          - name: db_name
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: db_name
          - name: db_host
            value: "db"
          - name: db_port
            value: "5432"
      - name: collect-static
        image: search-engine-webserver:latest
        imagePullPolicy: Never
        command: ['sh', '-c', 'cd /app/webserver/search && python manage.py collectstatic --noinput']
        volumeMounts:
        - name: static-files
          mountPath: /app/webserver/search/collected_static

      containers:
      - name: django
        env:
        - name: db_psw
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: db_user_name
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: name
        - name: db_name
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: db_name
        - name: db_host
          value: "db"
        - name: db_port
          value: "5432"
        args: [web]
        image: search-engine-webserver:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "4Gi"
          requests:
            memory: "1Gi"
        volumeMounts:
        - name: static-files
          mountPath: /app/webserver/search/collected_static

      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: static-files
          mountPath: /app/webserver/search/collected_static
        - name: nginx-webserver-config
          mountPath: /etc/nginx/conf.d

      volumes:
      - name: static-files
        emptyDir: {}
      - name: nginx-webserver-config
        configMap:
          name: nginx-webserver-config
