apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver-worker
  name: webserver-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver-worker
  template:
    metadata:
      labels:
        app: webserver-worker
    spec:
      containers:
        - args:
            - webserver_worker
          image: search-engine-webserver:latest
          name: webserver-worker
          imagePullPolicy: Never
          env:
            - name: db_psw
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: db_user_name
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: name
            - name: db_name
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: db_name
            - name: db_host
              value: "db"
            - name: db_port
              value: "5432"
          livenessProbe:
            exec:
              command:
                - celery
                - -A
                - search
                - inspect
                - ping
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            limits:
              memory: "4Gi"
            requests:
              memory: "1Gi"
