apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: webserver-worker
  name: webserver-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webserver-worker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: webserver-worker
    spec:
      containers:
        - args:
            - webserver_worker
          env:
            - name: MONGODB_URI
              value: mongodb://root:example@mongodb:27017/
          image: search-engine-webserver:latest
          name: webserver-worker
          volumeMounts:
            - mountPath: /app/webserver/search
              name: webserver-worker-claim1
      restartPolicy: Always
      volumes:
        - name: webserver-worker-claim1
          persistentVolumeClaim:
            claimName: webserver-worker-claim1
